// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/error/v1/error.proto

package errorv1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Step                 string            `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	Reason               string            `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Field                string            `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`
	Source               string            `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0006e8263ab055, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}

func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}

func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}

func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}

func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Error) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *Error) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Error) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Error) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Error) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Internal struct {
	Code                 string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	IdentifierCode       string            `protobuf:"bytes,2,opt,name=identifier_code,json=identifierCode,proto3" json:"identifier_code,omitempty"`
	Description          string            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Internal) Reset()         { *m = Internal{} }
func (m *Internal) String() string { return proto.CompactTextString(m) }
func (*Internal) ProtoMessage()    {}
func (*Internal) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0006e8263ab055, []int{1}
}

func (m *Internal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Internal.Unmarshal(m, b)
}

func (m *Internal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Internal.Marshal(b, m, deterministic)
}

func (m *Internal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Internal.Merge(m, src)
}

func (m *Internal) XXX_Size() int {
	return xxx_messageInfo_Internal.Size(m)
}

func (m *Internal) XXX_DiscardUnknown() {
	xxx_messageInfo_Internal.DiscardUnknown(m)
}

var xxx_messageInfo_Internal proto.InternalMessageInfo

func (m *Internal) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Internal) GetIdentifierCode() string {
	if m != nil {
		return m.IdentifierCode
	}
	return ""
}

func (m *Internal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Internal) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Response defines public error response format
type Response struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Internal             *Internal `protobuf:"bytes,2,opt,name=internal,proto3" json:"internal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b0006e8263ab055, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}

func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}

func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}

func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}

func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetInternal() *Internal {
	if m != nil {
		return m.Internal
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "rzp.common.error.v1.Error")
	proto.RegisterMapType((map[string]string)(nil), "rzp.common.error.v1.Error.MetadataEntry")
	proto.RegisterType((*Internal)(nil), "rzp.common.error.v1.Internal")
	proto.RegisterMapType((map[string]string)(nil), "rzp.common.error.v1.Internal.MetadataEntry")
	proto.RegisterType((*Response)(nil), "rzp.common.error.v1.Response")
}

func init() { proto.RegisterFile("common/error/v1/error.proto", fileDescriptor_6b0006e8263ab055) }

var fileDescriptor_6b0006e8263ab055 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0x49, 0xd3, 0x5f, 0x7e, 0x13, 0x7e, 0x7f, 0xd8, 0x8a, 0x86, 0x8a, 0x50, 0x7a, 0xb1,
	0x20, 0xa4, 0xa6, 0x5e, 0xd4, 0xde, 0xac, 0x45, 0x3c, 0x78, 0xc9, 0xc1, 0x83, 0x14, 0x24, 0x26,
	0x53, 0x08, 0xb6, 0xbb, 0x61, 0xb3, 0x8d, 0xb4, 0x1f, 0xc5, 0x8f, 0xe4, 0x97, 0xf1, 0x2b, 0x48,
	0x66, 0x63, 0xad, 0x1a, 0xbd, 0x79, 0x7b, 0xef, 0xcd, 0x9b, 0xdd, 0x79, 0xc3, 0xc0, 0x6e, 0x2c,
	0xe6, 0x73, 0xc1, 0xfb, 0x28, 0xa5, 0x90, 0xfd, 0x22, 0xd0, 0xc0, 0xcf, 0xa4, 0x50, 0x82, 0xb5,
	0xe4, 0x2a, 0xf3, 0xb5, 0xc1, 0xd7, 0x7a, 0x11, 0x74, 0x1f, 0x4d, 0xb0, 0xc7, 0x25, 0x61, 0x0c,
	0x1a, 0xb1, 0x48, 0xd0, 0x33, 0x3a, 0x46, 0xef, 0x77, 0x48, 0x98, 0x75, 0xc0, 0x4d, 0x30, 0x8f,
	0x65, 0x9a, 0xa9, 0x54, 0x70, 0xcf, 0xa4, 0xd2, 0xa6, 0x54, 0x76, 0xe5, 0x0a, 0x33, 0xcf, 0xd2,
	0x5d, 0x25, 0x66, 0xdb, 0xd0, 0x94, 0x18, 0xe5, 0x82, 0x7b, 0x0d, 0x52, 0x2b, 0xc6, 0xb6, 0xc0,
	0x9e, 0xa6, 0x38, 0x4b, 0x3c, 0x9b, 0x64, 0x4d, 0x4a, 0x77, 0x2e, 0x16, 0x32, 0x46, 0xaf, 0xa9,
	0xdd, 0x9a, 0xb1, 0x73, 0x70, 0xe6, 0xa8, 0xa2, 0x24, 0x52, 0x91, 0xf7, 0xab, 0x63, 0xf5, 0xdc,
	0x41, 0xcf, 0xaf, 0x49, 0xe0, 0xd3, 0xf4, 0xfe, 0x55, 0x65, 0x1d, 0x73, 0x25, 0x97, 0xe1, 0xba,
	0xb3, 0x3d, 0x84, 0x3f, 0xef, 0x4a, 0xec, 0x3f, 0x58, 0xf7, 0xb8, 0xac, 0x52, 0x96, 0xb0, 0x1c,
	0xab, 0x88, 0x66, 0x0b, 0xac, 0xe2, 0x69, 0x72, 0x6a, 0x1e, 0x1b, 0xdd, 0x67, 0x03, 0x9c, 0x4b,
	0xae, 0x50, 0xf2, 0x68, 0x56, 0xbb, 0x9f, 0x7d, 0xf8, 0x97, 0x26, 0xc8, 0x55, 0x3a, 0x4d, 0x51,
	0xde, 0x52, 0x59, 0x3f, 0xf2, 0xf7, 0x4d, 0x1e, 0xd5, 0x2c, 0xd2, 0xfa, 0xbc, 0xc8, 0x8b, 0x8d,
	0xb8, 0x0d, 0x8a, 0x7b, 0x50, 0x1b, 0xf7, 0x75, 0x9e, 0x9f, 0x49, 0xfc, 0x00, 0x4e, 0x88, 0x79,
	0x26, 0x78, 0x8e, 0xec, 0x10, 0x6c, 0xfa, 0x95, 0x3a, 0xdd, 0x41, 0xfb, 0xeb, 0xed, 0x87, 0xda,
	0xc8, 0x4e, 0xc0, 0x49, 0xab, 0xf1, 0xe8, 0x69, 0x77, 0xb0, 0xf7, 0x6d, 0x86, 0x70, 0x6d, 0x3f,
	0xeb, 0xdf, 0xec, 0x7c, 0xb8, 0xdd, 0x21, 0x81, 0x22, 0x78, 0x32, 0x5b, 0xe1, 0x2a, 0x9b, 0x8c,
	0xa8, 0x3a, 0xa1, 0xff, 0x26, 0xd7, 0xc1, 0x5d, 0x93, 0x8e, 0xfa, 0xe8, 0x25, 0x00, 0x00, 0xff,
	0xff, 0x3d, 0x53, 0x12, 0x1d, 0xf3, 0x02, 0x00, 0x00,
}
