sonar.projectKey=razorpay_trino-gateway_UT
sonar.projectName=trino-gateway
sonar.organization=razorpay

sonar.sources=.
sonar.exclusions=vendor/**,**/*_test.go,**/mock/**,rpc/**/*.pb.go,rpc/**/*.twirp.go,web/**,third_party/**,.agents/**,.claude/**,.cursor/**,.gemini/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=test-report.json

sonar.host.url=https://sonar.razorpay.com
