[app]
    appEnv              = "default"
    serviceName         = "trino-client"
    hostname            = "trino.client.razorpay.com"
    port                = 8000
    metricsPort         = 8080
    shutdownTimeout     = 2
    shutdownDelay       = 2

[db]
    dialect             = "trino"
    protocol            = "tcp"
    url                 = "localhost"
    port                = 8080
    username            = "trino-client"
    password            = "trino-client"
    catalog             = "trino-client-catalog"
    schema              = "trino-client-schema"
    DSN                 = "http://user@localhost:8080?catalog=default&schema=public"

[auth]
    [auth.token]
        api             = "1234"
        debug           = "4567"