[app]
    gitCommitHash                = "dev-docker"
    logLevel                     = "debug"

[db]
    [db.ConnectionConfig]
        url                      = "trino_gateway_mysql"
        port                     = 3306

[gateway]
    defaultRoutingGroup          = "dev"

[trinoRest]
    appEnv              = "default"
    serviceName         = "trino-rest"
    hostname            = "localhost"
    port                = 8000
    metricsPort         = 8080
    shutdownTimeout     = 2
    shutdownDelay       = 2
    maxRecords          = 5000
    isAuthDelegated     = false
    [trinoRest.trinoBackendDb]
        dialect             = "trino"
        protocol            = "tcp"
        url                 = "trino_local"
        port                = 8080
        username            = "user"
        password            = ""
        catalog             = "default"
        schema              = "public"
        DSN                 = "http://user@trino_local:8080?catalog=default&schema=public"
