[app]
    appEnv                = "default"
    serviceName           = "trino-gateway"
    hostname              = "trino-gateway.razorpay.in"
    port                  = "0.0.0.0:9400"
    shutdownTimeout       = 2
    shutdownDelay         = 2
    gitCommitHash         = "nil"

[db]
    dialect               = "mysql"
    protocol              = "tcp"
    url                   = "db"
    port                  = "3306"
    username              = "trino-gateway"
    password              = "trino-gateway"
    sslMode               = "require"
    name                  = "trino-gateway"
    maxOpenConnections    = 5
    maxIdleConnections    = 5
    connectionMaxLifetime = 0

[tracing]
    disabled              = false
    localAgentHostPort    = "jaeger:6831"

[auth]
    username = "key"
    password = "secret"

[queue]
    driver                = "redis"
    [queue.redis]
        driver            = "redis"
        host              = "redis"
        port              = 6379
        database          = 0
        password          = ""

[job]
    user_approve          = "user_approve"

[worker]
    name                  = "user_approve"
    max_concurrency       = 1
    wait_time             = "10s"
    retry_delay           = "30s"
