[app]
    logLevel              = "info"
[monitor]
    interval              = "20s"
    healthCheckSql        = "SHOW SCHEMAS FROM hive"
[gateway]
    ports                 = [8080, 8081, 8082, 8083]
