#!/usr/bin/env bash
# Generate a structured E2E test report in Markdown.
#
# Usage:
#   generate-report.sh \
#     --pr-url <url> \
#     --services "svc1,svc2" \
#     --flows "flow1|flow2" \
#     --results <results.json> \
#     [--output <file.md>]
#
# results.json format:
# {
#   "test_cases": [
#     {
#       "name": "Happy path refund bypass",
#       "type": "happy_path|negative|integration|state_verification",
#       "status": "pass|fail|skip",
#       "details": "Optional details or error message",
#       "fix_applied": "Optional fix description"
#     }
#   ],
#   "failures": ["description1"],
#   "fixes_applied": ["fix1"],
#   "entity_changes": ["change1"]
# }

set -euo pipefail

PR_URL=""
SERVICES=""
FLOWS=""
RESULTS_FILE=""
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --pr-url) PR_URL="$2"; shift 2 ;;
    --services) SERVICES="$2"; shift 2 ;;
    --flows) FLOWS="$2"; shift 2 ;;
    --results) RESULTS_FILE="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$PR_URL" || -z "$RESULTS_FILE" ]]; then
  echo "Error: --pr-url and --results are required" >&2
  exit 1
fi

if [[ ! -f "$RESULTS_FILE" ]]; then
  echo "Error: Results file not found: $RESULTS_FILE" >&2
  exit 1
fi

TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M UTC')

# Parse results JSON
TOTAL=$(jq '.test_cases | length' "$RESULTS_FILE")
PASSED=$(jq '[.test_cases[] | select(.status == "pass")] | length' "$RESULTS_FILE")
FAILED=$(jq '[.test_cases[] | select(.status == "fail")] | length' "$RESULTS_FILE")
SKIPPED=$(jq '[.test_cases[] | select(.status == "skip")] | length' "$RESULTS_FILE")
NUM_FAILURES=$(jq '.failures | length' "$RESULTS_FILE")
NUM_FIXES=$(jq '.fixes_applied | length' "$RESULTS_FILE")

if [[ "$FAILED" -eq 0 ]]; then
  VERDICT="PASS"
else
  VERDICT="FAIL"
fi

# Generate report
generate() {
cat <<REPORT
# E2E Test Report

| Field | Value |
|-------|-------|
| **PR** | $PR_URL |
| **Timestamp** | $TIMESTAMP |
| **Verdict** | **$VERDICT** |
| **Tests** | $PASSED passed / $FAILED failed / $SKIPPED skipped (total: $TOTAL) |

## Services Deployed

$(echo "$SERVICES" | tr ',' '\n' | sed 's/^/- /')

## Flows Tested

$(echo "$FLOWS" | tr '|' '\n' | sed 's/^/- /')

## Test Cases

| # | Name | Type | Status | Details |
|---|------|------|--------|---------|
$(jq -r '.test_cases | to_entries[] | "| \(.key + 1) | \(.value.name) | \(.value.type) | \(if .value.status == "pass" then "PASS" elif .value.status == "fail" then "FAIL" else "SKIP" end) | \(.value.details // "-") |"' "$RESULTS_FILE")

$(if [[ "$NUM_FAILURES" -gt 0 ]]; then
echo "## Failures Detected"
echo ""
jq -r '.failures[] | "- " + .' "$RESULTS_FILE"
fi)

$(if [[ "$NUM_FIXES" -gt 0 ]]; then
echo "## Fixes Applied"
echo ""
jq -r '.fixes_applied[] | "- " + .' "$RESULTS_FILE"
fi)

$(if jq -e '.entity_changes | length > 0' "$RESULTS_FILE" >/dev/null 2>&1; then
echo "## Entity/State Changes Observed"
echo ""
jq -r '.entity_changes[] | "- " + .' "$RESULTS_FILE"
fi)

---
*Generated by e2e-orchestrator skill*
REPORT
}

if [[ -n "$OUTPUT" ]]; then
  generate > "$OUTPUT"
  echo "Report written to: $OUTPUT"
else
  generate
fi
