[trino-rest]
    appEnv              = "default"
    serviceName         = "trino-rest"
    hostname            = "localhost"
    port                = 8000
    metricsPort         = 8080
    shutdownTimeout     = 2
    shutdownDelay       = 2
    maxRecords          = 5000
    [trino-backend-db]
        dialect             = "trino"
        protocol            = "tcp"
        url                 = "localhost"
        port                = 8080
        username            = "user"
        password            = "user"
        catalog             = "default"
        schema              = "public"
        DSN                 = "http://user@trino_rest:8080?catalog=default&schema=public"
